### ISSUE TITLE
Balance enemies and waves

### ISSUE THREAD

**Issue by ArthurGW** [GavRobbs/embargo#17]
The playtest revealed the game to be a bit unbalanced, with a lot of enemies early on being quite hard to handle, a middle period where you had less trouble as you had plenty of turrets, then eventually (wave X) you just ran out of building space.

Some ideas for balancing:
- have only scouts in the first wave
- make the scouts a bit weaker, so you can defeat the wave with only a handful of turrets
- possibly add a third enemy type, which is just a stronger scout and comes between scout and battle tank. This could just use the scout model with a red dome or something for ease of implementation
- as waves go on, gradually increase battle tank numbers (and "advanced scout"?). Maybe reduce (basic) scout numbers, so it doesn't become so much about the number of turrets you have, more about their strength

**Comment by GavRobbs** [comment]
There was actually a logic bug that was making the machineguns too powerful, but I fixed it. I increased enemy speed and HP as the wave progressed.
