### ISSUE TITLE
Important cosmetic changes

### ISSUE THREAD

**Issue by ArthurGW** [GavRobbs/embargo#20]
A list of changes which are only really cosmetic, but would significantly improve gameplay.

- [x] Add an indicator of how many levels/waves there are to go, to add a target for the user
- [x] Remove all non-functional control buttons, so they all do something (last minute thing in case we implement them)
- [x] Add cost popups to all construction buttons - turrets, drones 3 & 4, so when you hover you know what it will cost. Or just add text to the button

**Comment by GavRobbs** [comment]
Completed the wave indicator.
